### ISSUE TITLE
No form errors after login fail.

### ISSUE THREAD

**Issue by mrcmorales** [nucleos/NucleosUserBundle#181]
Hello,

With the new 1.6.0 version that use symfony forms, the form from login  has not any error after the login fail.

I think it is because the form isn't submitted: https://github.com/nucleos/NucleosUserBundle/blob/main/src/Action/LoginAction.php#L94

For the other hand error var is always null, So I can't catch the error using this variable neither.

https://github.com/nucleos/NucleosUserBundle/blob/main/src/Action/LoginAction.php#L106

Thank you

**Comment by core23** [comment]
Thanks for reporting. There is a bugfix in #182
