### ISSUE TITLE
Remove buttons from Forms

### ISSUE THREAD

**Issue by fkrauthan** [nucleos/NucleosUserBundle#188]
## Feature Request

I would prefer if the default forms shipped with the bundle (`LoginFormType`) would not contain a button. It makes the form class a lot more reusable as currently I have to create form extension just to remove it as otherwise the styling of my page would be off.

**Comment by core23** [comment]
The idea was to define all form related inputs (and buttons) inside the php classes. So you just need to call `form_widget(form)` inside the template to render the whole form. The form rendering will also respect the current form theme (e.g. bootstrap) so you don't need any special handling for the form button when changing the theme.

I know that there is a [symfony best practice for forms](https://symfony.com/doc/current/best_practices.html#add-form-buttons-in-templates) but they are talking about reusable forms. The login form should not be used inside an other application context.

**Comment by fkrauthan** [comment]
I guess that makes sense. Even though I would assume most people will have there fully custom login theme where anything beyond the minimal required fields can be annoying.

**Comment by core23** [comment]
There are some other hacks if you don't want some form elements:

```twig
{% set foo = form['some_field'].setRendered() %}

```

```twig
{% set foo %}{{ form_widget(form.someField) }}{% endset %}
```

I will leave the button element inside the PHP code for the given reasons, sorry.

**Comment by fkrauthan** [comment]
Yeah that's fair. To be quiet honest for my immediate project I moved to a fully custom authentication system. But I will keep an eye on this project for potential future projects.

**Comment by core23** [comment]
IMHO the new symfony security system (in combination with the MakeBundle) solves most of the basic auth stuff that is part of the FOSUserBundle and this bundle. This bundle is for the lazy people ;)
