### ISSUE TITLE
Extending Doctrine\UserManager

### ISSUE THREAD

**Issue by fodger** [nucleos/NucleosUserBundle#244]
## Question
Hi,
since Doctrine\UserManager has become a final class we can't extend anymore, while it was possible in fosuserbundle.

Which is the right way with Nucleos ?

Thanks.

**Comment by core23** [comment]
You could use the [service decoration pattern](https://symfony.com/doc/current/service_container/service_decoration.html) or create a new service that uses some parts of the `UserManager` api.

If non of this is possible and you can provide a valid use case, you can open a PR which removes `final` from the class.

**Comment by fodger** [comment]
I had defined my own manager :
```
nucleos_user:
    service:
        user_manager: myuser.manager
```
myuser.manager extended UserManager like it was did with fos bundle.
But now I had to redeclare methods from interface like deleteUser, getClass ... it was simpler to extends before.

**Comment by core23** [comment]
As mentioned before, if you provide a use case where you really need the extension, you can open a PR.

This project started as a FOSUserBundle clone of the latest master branch, but it evolved in some parts. I made some adjustments that would help to maintain the project in a long term. E.g. closing most of the classes was a design decision to allow more minor refactorings without breaking the public API.
