### ISSUE TITLE
[Doc] Missing overriding part for twig templating

### ISSUE THREAD

**Issue by fodger** [nucleos/NucleosUserBundle#245]
## Question
Hi there,
I read the documentation, but I didn't find any part to override login.html.twig template.

While I follow the symfony reference, it doesn't works.
https://symfony.com/doc/4.4/controller/error_pages.html#overriding-the-default-error-templates

The created twig root path :
templates/bundles/user-bundle/Security/login.html.twig

**Comment by fodger** [comment]
My bad, it was a stupid mistake in my vhost.

**Comment by fodger** [comment]
Ok, if some else if looking for with SF > 4.x : 
- just create the dir in project dir templates/NucleosUserBundle/Security
- override the desired twig file (login.html.twig etc.)

**Comment by domhaas** [comment]
For anybody having the same issue - with my symfony 4.4 installation the correct folder is e.g.:
`templates/bundles/NucleosUserBundle/Security/login.html.twig`
