### ISSUE TITLE
Allow extending RequestPasswordFormType

### ISSUE THREAD

**Issue by fodger** [nucleos/NucleosUserBundle#294]
### Environment
SF 4.4

#### Packages
"nucleos/user-bundle": "*", (1.8)
"nucleos/profile-bundle": "*", (1.4)

#### PHP version
PHP 7.4

## Subject

Extending RequestPasswordFormType occures error while accessing to email property

## Steps to reproduce

Extends form using getParent() : 
```
    public function getParent()
    {
        return RequestPasswordFormType::class;
    }
```

## Expected results
Form printed like FOSUserbundle did.

## Actual results
Neither the property "email" nor one of the methods "email()", "getemail()"/"isemail()"/"hasemail()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView".

**Comment by core23** [comment]
This feature does not exist, because there is no `RequestPassword` model class to map this data.

Feel free to provide a PR which add this feature @fodger .
