### ISSUE TITLE
Mongodb schema create error

### ISSUE THREAD

**Issue by jerzypinkas** [nucleos/NucleosUserBundle#35]
With MongoDB ODM and default Installation from documentation on 'Step 7':

`php bin/console doctrine:mongodb:schema:create --index`

make response

`The field 'safe' is not valid for an index specification. Specification: { key: { usernameCanonical: 1 }, safe: true, unique: true, background: false, ns: "DATABASE.User", name: "usernameCanonical_1" }`

**Comment by core23** [comment]
This must be a copy & paste error when importing the FOS code.

Can you provide a PR that removes all unnecessary fields(e.g. safe) here:
https://github.com/nucleos/NucleosUserBundle/blob/master/src/Resources/config/doctrine-mapping/User.mongodb.xml
https://github.com/nucleos/NucleosUserBundle/blob/master/src/Resources/config/doctrine-mapping/Group.mongodb.xml

**Comment by jerzypinkas** [comment]
vendor/nucleos/user-bundle/src/Resources/config/doctrine-mapping/User.mongodb.xml
After comment out lines 20, 25, 30 (where is <option name="safe" value="true"/>) everything is OK, a message is: 'Updated indexes for all classes'

similar 'safe option' exists in file
vendor/nucleos/user-bundle/src/Resources/config/doctrine-mapping/Group.mongodb.xml
but I didn't test it

Also, I've found those issues:
https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2963

https://stackoverflow.com/questions/41036442/mongodb-dump-from-3-2-restore-with-3-4-error-index-safe-null

**Comment by core23** [comment]
Can you drop the `safe` option for mongo < 4?

**Comment by jerzypinkas** [comment]
What do you mean? I don't want to install another version of mongo.

**Comment by core23** [comment]
Sorry for the late response.

Can you create a PR which removes these lines @jerzypinkas ?
https://github.com/nucleos/NucleosUserBundle/blob/master/src/Resources/config/doctrine-mapping/User.mongodb.xml#L20
https://github.com/nucleos/NucleosUserBundle/blob/master/src/Resources/config/doctrine-mapping/User.mongodb.xml#L25
https://github.com/nucleos/NucleosUserBundle/blob/master/src/Resources/config/doctrine-mapping/User.mongodb.xml#L30
...

**Comment by core23** [comment]
Can you checkout the latest `main-dev` version @jerzypinkas ?
