### ISSUE TITLE
deprecation message symfony 5.3

### ISSUE THREAD

**Issue by ghost** [nucleos/NucleosUserBundle#364]
Hello,

Following migration to Symfony 5.3, I have the following deprecation message: 

- Since symfony/security-bundle 5.3: The "security.encoder_factory" service is deprecated, use "security.password_hasher_factory" instead. It is being referenced by the "nucleos_user.util.password_updater" service.

 - Since symfony/framework-bundle 5.3: The "session" service and "SessionInterface" alias are deprecated, use "$requestStack->getSession()" instead. It is being referenced by the "nucleos_user.session" alias.

Any idea on how to resolve that?

**Comment by core23** [comment]
> * Since symfony/security-bundle 5.3: The "security.encoder_factory" service is deprecated, use "security.password_hasher_factory" instead. It is being referenced by the "nucleos_user.util.password_updater" service.

Might relate to https://github.com/nucleos/NucleosUserBundle/issues/274

> * Since symfony/framework-bundle 5.3: The "session" service and "SessionInterface" alias are deprecated, use "$requestStack->getSession()" instead. It is being referenced by the "nucleos_user.session" alias.

The `nucleos_user.session` alias is new to me. Can you examine where this alias is defined?

**Comment by ghost** [comment]
I found one reference in file nucleos/user-bundle/src/DependencyInjection/NucleosUserExtension.php
 if ($this->sessionNeeded) {
            // Use a private alias rather than a parameter, to avoid leaking it at runtime (the private alias will be removed)
            $container->setAlias('nucleos_user.session', new Alias('session', false));
 }
