### ISSUE TITLE
Support for impersonating users

### ISSUE THREAD

**Issue by AntonioCS** [nucleos/NucleosUserBundle#381]
## Feature Request
Hey,
I've followed the steps mentioned here: https://symfony.com/doc/current/security/impersonating_user.html
Then I tried using the `switch_user` url thing and nothing worked.

Am I doing something wrong or is this something that somehow needs to be enabled somewhere in Nucleos code?
Thanks

**Comment by core23** [comment]
This is a symfony feature. There is no special handling for this bundle.
