### ISSUE TITLE
Is there a way to add features to the create command?

### ISSUE THREAD

**Issue by AntonioCS** [nucleos/NucleosUserBundle#386]
## Feature Request

Hey,

My user table has some extra fields that are required and I take care of this when I'm creating a user using a GUI, but when I setup the project (locally or in a sandbox) I run the `nucleos:user:create` to create a super admin, but since I can't pass other parameters I get some errors in other parts of the code.

I've thought about decorating the service command but this doesn't seem viable as `execute` is a protected method so there is no way for me to add anything on top of that (I think).
Using a compiler pass seems to not work because the `CreateUserCommand` class is final so if I were to replace it with a command that extended `CreateUserCommand` I would not be able to override `execute`.

So is there a way for you guys to add something that would allow me to add parameters or just a way to extend this command?

**Comment by core23** [comment]
It's no featuring I'm planing to add, but you can provide a PR with an extension point.

Maybe you can use the event dispatcher to add custom logic when creating a new users.
