### ISSUE TITLE
Why this over SonataUserBundle?

### ISSUE THREAD

**Issue by haivala** [nucleos/NucleosUserBundle#39]
## Question

FosUserBundle is going to be implemented in SonataUserBundle. am I right? Why should I update FosUserBunlde to this while I wait it to happen?

**Comment by core23** [comment]
This bundle has a different purpose. SonataUserBundle will provide a full feature frontend and a CRUD backend. 

NucleosUserBundle provides a simple auth component that is reuseable. If you want a login, you should require the profile bundle. If you need a backend, you should require the user admin bundle. The nucleos bundles are more atomic than the sonata bundle.
