### ISSUE TITLE
Cannot install this bundle due to outdated package...

### ISSUE THREAD

**Issue by alwaeles** [nucleos/NucleosUserBundle#391]
## Question

I'm trying to install `nucleos/user-bundle` but I get a deprecation error:

```
- nucleos/user-bundle[1.11.0, ..., 1.12.x-dev] require egulias/email-validator ^2.1.10 -> found egulias/email-validator[dev-master, 2.1.10, ..., 2.1.x-dev (alias of dev-master)]
but the package is fixed to 3.1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

I've found the pull request #307 that has been closed without explaination so I'm just wondering.

I'm using the latest stable Symfony: 5.3.4.

Thanks...

**Comment by core23** [comment]
I only merge dependabot PRs that can be merged without any refactorings. 

Feel free to reopen a PR that will support the new `egulias/email-validator` version.

**Comment by gomcodoctor** [comment]
any update on this?

**Comment by core23** [comment]
No, I'n not actively working on this.

This is an open source community project, so feel free to provide a PR with a fix @gomcodoctor
