### ISSUE TITLE
Applying the documented password restrictions breaks when changing password with different new passwords

### ISSUE THREAD

**Issue by AubreyHewes** [nucleos/NucleosUserBundle#396]
#### Packages

```
nucleos/user-bundle                       1.11.0
```

#### PHP version

```
7.4.12
```

## Subject

Using the `plainPassword` pattern validator described at [1.10.x/security.html#password-restrictions](https://docs.nucleos.rocks/projects/user-bundle/en/1.10.x/security.html#password-restrictions) breaks changing password with _different_ new passwords.

## Steps to reproduce

1. Add the configuration at [1.10.x/security.html#password-restrictions](https://docs.nucleos.rocks/projects/user-bundle/en/1.10.x/security.html#password-restrictions)
2. Login
3. Go to `/change-password`
4. Enter a _different_ password for both new-password fields (new password and new password confirmation must be different)
5. Submit the form

## Expected results

A validation error; passwords are not the same

## Actual results

A fatal error; 

````
Expected argument of type "string", "null" given

File: vendor/nucleos/user-bundle/src/Validator/Constraints/PatternValidator.php
Line: 29
````

## Analysis

I believe the reason is that as the form `RepeaterType` has different values the `ChangePassword` form model value is not set (so is null) and the then executed `PatternValidator` expects a string value.

## Possible solution

Changing the `PatternValidator` to return instead of throwing an exception when the value is null solves the issue; _though I am unsure if this is the correct solution_.

**Comment by core23** [comment]
> Changing the `PatternValidator` to return instead of throwing an exception when the value is null solves the issue; _though I am unsure if this is the correct solution_.

Can you provide a PR with this fix?
