### ISSUE TITLE
Reset Password via SymfonyCasts?

### ISSUE THREAD

**Issue by Hanmac** [nucleos/NucleosUserBundle#417]
## Feature Request

Would it make sense to simplify this bundle by using https://github.com/SymfonyCasts/reset-password-bundle ?
We could still use our own events if needed.

**Comment by core23** [comment]
Thanks for your advice, but I don't want any integration with our bundles for this project.

The idea behind this project is to provide an easy user management solution without installing a bunch of other libs. Relying on other projects can be risky. You have to update the docs very often as there are more potential BC breaks after each third party major update.

Today you don't need this bundle anymore and can use several `make:` commands to generate everything user related.

**Comment by Hanmac** [comment]
i was waiting for the AdminBundle version of this to support (soon to be) released Sonata to update to Symfony 5, so i can have this stuff in Sonata. 

Or do you mean its better to just drop it?

Or what about your Issue there, using Authenticator-based Security? https://github.com/nucleos/NucleosUserBundle/issues/274#issuecomment-895961672
