### ISSUE TITLE
Adding Validation Groups for Override

### ISSUE THREAD

**Issue by Hanmac** [nucleos/NucleosUserBundle#604]
## Feature Request

i would need to remove some of the Validations when using this bundle in one of my projects.

Long Story short, i need to be able to have the users share an email address, and the Unique Email Address Validator can't be disabled.

https://symfony.com/doc/current/bundles/override.html#validation-metadata says, the best way how to make this done, would be to have an option in the bundle to change the validation group.

**Comment by core23** [comment]
Unfortunately this can't be done on the stable branch, because it will change the expected behavior. 

I've created a new `3.0.x` branch where you can add validation groups to the existing [validation.xml](https://github.com/nucleos/NucleosUserBundle/blob/2.2.x/src/Resources/config/validation.xml).
