### ISSUE TITLE
Serialization error for rememberme token after upgrading to 2.x 

### ISSUE THREAD

**Issue by gaetan-petit** [nucleos/NucleosUserBundle#711]
## Question

After upgrading to 2.x, we are running into a serialization issue in `Symfony\Component\Security\Http\Firewall\ContextListener:198`
The serialization of the token fails because on of its property is a File object.

`Serialization of 'Symfony\Component\HttpFoundation\File\File' is not allowed`

I suspect it could be because the `__serialize()` method were remove from the User Bundle in https://github.com/nucleos/NucleosUserBundle/pull/543 by @core23 

I have no clue of what should be done to fix this.
Could you help us?

**Comment by core23** [comment]
If you extend the user with a complex property, you may implement the Serializable interface again

**Comment by gaetan-petit** [comment]
Ok thanks @core23 this is what I did in the meantime. It's nice to have a confirmation from you.
