### ISSUE TITLE
Login form uses `getMessage()` instead of `getMessageKey()`

### ISSUE THREAD

**Issue by pohlm01** [nucleos/NucleosUserBundle#725]
## Description
I have trouble displaying a meaningful message to the user on the login screen if a [`TooManyLoginAttemptsAuthenticationException`](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Security/Core/Exception/TooManyLoginAttemptsAuthenticationException.php) is thrown.
This is because, this exception does return an empty string on a `getMessage()` call, which I cannot translate to a meaningful message.

During troubleshooting, it turned out that Symphony mentions[^1] to never display the message of an `AuthenticationException`, as it may contain sensitive data.
A good example for sensitive data can be found in Symphony itself. [When checking credentials](https://github.com/symfony/security-http/blob/19f7b5f5d20879a976d6d376e359bc975dfc6002/EventListener/CheckCredentialsListener.php#L69), the message contains the information that the user does exist, but the password is wrong. Generally, the user should not know this information, but it gets currently leaked [here](https://github.com/nucleos/NucleosUserBundle/blob/37af16c9eb11517b9b9a0e17a4a06c90e649d6aa/src/Form/Type/LoginFormType.php#L67C43-L67C43).

I propose to replace the [questionable `getMessage()` call](https://github.com/nucleos/NucleosUserBundle/blob/37af16c9eb11517b9b9a0e17a4a06c90e649d6aa/src/Form/Type/LoginFormType.php#L67C43-L67C43) in the login screen with the save `getMessageKey()` counterpart. Any opinions on that?

[^1]: [Symphony mentions](https://symfony.com/doc/current/security/custom_authenticator.html) that: "_**Caution**: Never use `$exception->getMessage()` for `AuthenticationException` instances. This message might contain sensitive information that you don't want to be publicly exposed. Instead, use `$exception->getMessageKey()` and `$exception->getMessageData()` like shown in the full example above. Use [CustomUserMessageAuthenticationException](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Security/Core/Exception/CustomUserMessageAuthenticationException.php) if you want to set custom error messages_."

**Comment by core23** [comment]
Can you provide a PR with a fix @pohlm01 ?

**Comment by pohlm01** [comment]
Sure. I opened two PRs, one on the default branch, and one on the 1.13.x branch. I wasn't too sure about the maintenance status of the 1.13.x branch, but unfortunately this is where I would need the fix…
