### ISSUE TITLE
Roles field override

### ISSUE THREAD

**Issue by Eloar** [nucleos/NucleosUserBundle#88]
## Question

In my data model there is system dictionary of roles. User entity is associated with roles in n-n way. How may I override array field from Bundle as association in my code?

**Comment by core23** [comment]
Sorry I can't help here. I don't provide any general advice how you do things in symfony or doctrine.

Also please give some more information / code if you want any assistance that is bundle related.

**Comment by Eloar** [comment]
The problem was due to definition of field `roles` as `array` in `src\Resources\config\doctrine-mapping\User.orm.xml`. Even thou I overrode all methods related to `roles` in `User` class I could not modify declaration in superclass mapping. It was so annoying I've dropped use of that bundle.
